kind: pipeline
type: docker
name: amd64

steps:
- name: build-linux-amd64
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - make --jobs=$(nproc) bin/linux/amd64/container-logs
  when:
    event:
    - push
    - pull_request
    - tag